stages:
  - build
  - publish
  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

build_job:
  stage: build
  tags:
    - mac
  only:
    - tags
  script:
    - git clone -q https://$GITLAB_USER:$GITLAB_PASSWORD@gitlab.es.gov.br/SGPRJ/espm-ci-secrets.git > /dev/null 2>&1
    - cp espm-ci-secrets/.env .
    - cp -r espm-ci-secrets/ios/* .
    - ./scripts/ios-build.sh
  artifacts:
    expire_in: 1 day
    paths:
      - platforms/ios/build/device/
      - fastlane
publish_job:
  stage: publish
  tags:
    - mac
  only:
    - tags
  script:
    - DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" fastlane ios beta
  dependencies:
    - build_job