version: 2
jobs:
  build-ionic:
    docker:
      - image: prodest/circleci-containers:node-ionic-aws-v1.1.0
    working_directory: ~/espm
    steps:
      - checkout
      - restore_cache:
          keys:
          - v5-dependencies-node_modules-{{ checksum "package-lock.json" }}
          - v5-dependencies-node_modules
      - run: npm install
      - run: npm run build:prod:android
      - save_cache:
          paths:
            - node_modules
          key: v5-dependencies-node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Get secrets
          command: |
            git clone -q https://gitlab-ci-token:$GITLAB_CI_TOKEN@gitlab.es.gov.br/SGPRJ/espm-ci-secrets.git > /dev/null 2>&1
            cp espm-ci-secrets/.env .
            cp espm-ci-secrets/android/* .
      - persist_to_workspace:
          root: ~/espm
          paths:
            - ./
  publish-prod:
    docker:
      - image: prodest/circleci-containers:mobile-android-v1.1.0
    working_directory: ~/espm
    steps:
      - attach_workspace:
          at: ./
      - run: cordova platform add android@7.1.1
      - run: cordova prepare android -f
      - run: cordova build android --release --buildconfig=build.json
      # - run: 
      #     name: Upload APK to Gitlab?
      #     command: 
      - run:
          name: Publish on Play Store Alpha
          command: node scripts/upload-apk.js platforms/android/app/build/outputs/apk/release/app-release.apk alpha br.gov.es.prodest.espm
workflows:
  version: 2
  main-workflow:
    jobs:
      - build-ionic:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - publish-prod:
          requires:
            - build-ionic
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}/ # v1.2.3
